name: Check Markdown links

on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 9 * * 1"

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Check links in markdown files
      uses: gaurav-nelson/github-action-markdown-link-check@v1
